packages:
  - packages/*
  - playground/*
  - docs

overrides:
  '@netlify/functions': '-'
  '@rolldown/pluginutils': 'catalog:'
  '@vitejs/plugin-vue': 'catalog:'
  '@vitejs/plugin-vue-jsx': 'catalog:'
  is-core-module: npm:@no-shims/is-core-module
  oxc-parser: 'catalog:'
  smartwrap: npm:@no-shims/smartwrap
  vite: 'catalog:'
  oxc-minify: 'catalog:'
  oxc-transform: 'catalog:'
  unplugin-vue-router>@vue-macros/common: latest
  '@babel/parser': 'catalog:'
  '@babel/traverse': 'catalog:'

defines:
  - &babel ^7.28.4
  - &nolebase ^2.18.2
  - &shiki ^3.13.0
  - &unocss ^66.5.2
  - &vitest ^3.2.4
  - &vlt 3.0.8
  - &vue ^3.5.22
  - &rolldown ^1.0.0-beta.40
  - &oxc ^0.92.0
  - &nuxt ^4.1.2
  - &stylex-extend ^0.7.1

catalog:
  '@babel/parser': *babel
  '@babel/traverse': *babel
  '@babel/types': *babel

  '@vue/language-core': *vlt
  vue-tsc: *vlt

  '@vitest/coverage-v8': *vitest
  '@vitest/ui': *vitest
  vitest: *vitest

  '@unocss/eslint-plugin': *unocss
  '@unocss/nuxt': *unocss
  '@unocss/reset': *unocss
  unocss: *unocss

  '@vue/compiler-core': *vue
  '@vue/compiler-dom': *vue
  '@vue/compiler-sfc': *vue
  '@vue/shared': *vue
  vue: *vue

  '@shikijs/vitepress-twoslash': *shiki
  shiki: *shiki

  '@nolebase/vitepress-plugin-enhanced-mark': *nolebase
  '@nolebase/vitepress-plugin-enhanced-readabilities': *nolebase
  '@nolebase/vitepress-plugin-git-changelog': *nolebase
  '@nolebase/vitepress-plugin-highlight-targeted-heading': *nolebase

  oxc-minify: *oxc
  oxc-parser: *oxc
  oxc-resolver: ^11.8.3
  oxc-transform: *oxc

  '@astrojs/vue': ^5.1.1
  '@iconify-json/logos': ^1.2.9
  '@iconify-json/ri': ^1.2.5
  '@nuxt/devtools': ^2.6.5
  '@nuxt/kit': *nuxt
  '@nuxt/schema': *nuxt
  '@rolldown/pluginutils': *rolldown
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rspack/core': ^1.5.7
  '@stylex-extend/core': *stylex-extend
  '@stylex-extend/vite': *stylex-extend
  '@stylexjs/stylex': ^0.15.4
  '@sxzz/eslint-config': ^7.2.3
  '@sxzz/prettier-config': ^2.2.4
  '@sxzz/test-utils': ^0.5.11
  '@types/node': ^24.5.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vueuse/core': ^13.9.0
  ast-kit: ^2.1.2
  ast-walker-scope: ^0.8.2
  astro: ^5.13.11
  bumpp: ^10.2.3
  change-case: ^5.4.4
  cspell: ^9.2.1
  esbuild: ^0.25.10
  eslint: ^9.36.0
  expect-type: ^1.2.2
  fast-glob: ^3.3.3
  get-port: ^7.1.0
  jiti: ^2.6.0
  local-pkg: ^1.1.2
  magic-string: ^0.30.19
  magic-string-ast: ^1.0.2
  monoman: ^0.7.2
  muggle-string: ^0.4.1
  neverthrow: ^8.2.0
  nuxt: *nuxt
  pkg-types: ^2.3.0
  prettier: ^3.6.2
  publint: ^0.3.13
  quansync: ^0.2.11
  quasar: ^2.18.5
  radix-vue: ^1.9.17
  rimraf: ^6.0.1
  rolldown: *rolldown
  rollup: ^4.52.2
  rollup-plugin-dts: ^6.2.3
  sirv: ^3.0.2
  taze: ^19.7.0
  ts-macro: ^0.3.6
  tsdown: ^0.15.4
  tsx: ^4.20.5
  type-fest: ^5.0.1
  typescript: ^5.9.2
  unconfig: ^7.3.3
  unplugin: ^2.3.10
  unplugin-combine: ^2.1.2
  unplugin-macros: ^0.18.2
  unplugin-oxc: ^0.5.2
  unplugin-quansync: ^0.4.4
  unplugin-raw: ^0.6.3
  unplugin-unused: ^0.5.3
  unplugin-utils: ^0.3.0
  unplugin-vue: ^7.0.1
  vite: ^7.1.7
  vite-hyper-config: ^0.7.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-vue-devtools: ^8.0.2
  vitepress: ^2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.3
  vitepress-plugin-llms: ^1.7.5
  webpack: ^5.101.3

peerDependencyRules:
  ignoreMissing:
    - search-insights
