# eslint yml/sort-keys: 'error'

catalog:
  '@stylexjs/stylex': ^0.8.0
  '@vue/compiler-core': ^3.5.12
  '@vue/compiler-dom': ^3.5.12
  '@vue/compiler-sfc': ^3.5.12
  '@vue/language-core': 2.1.8
  '@vue/reactivity': ^3.5.12
  '@vue/runtime-core': ^3.5.12
  '@vue/runtime-dom': ^3.5.12
  '@vue/shared': ^3.5.12
  typescript: ^5.6.3
  unplugin: ^1.14.1
  vite: ^5.4.10
  vite-plugin-stylex: ^0.12.0
  vue: ^3.5.12
  vue-tsc: 2.1.8
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
