# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.4.34
  '@vue/compiler-dom': ^3.4.34
  '@vue/compiler-sfc': ^3.4.34
  '@vue/language-core': 2.0.28
  '@vue/reactivity': ^3.4.34
  '@vue/runtime-core': ^3.4.34
  '@vue/runtime-dom': ^3.4.34
  '@vue/shared': ^3.4.34
  unplugin: ^1.12.0
  vite: ^5.3.5
  vue: ^3.4.34
  vue-tsc: 2.0.28
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
