packages:
  - packages/*
  - playground/*
  - docs

overrides:
  '@netlify/functions': '-'
  '@rolldown/pluginutils': 'catalog:'
  '@shikijs/core': 'catalog:'
  '@shikijs/transformers': 'catalog:'
  '@shikijs/types': 'catalog:'
  '@vitejs/plugin-vue': 'catalog:'
  '@vitejs/plugin-vue-jsx': 'catalog:'
  '@vue/language-core': 'catalog:'
  is-core-module: 'npm:@no-shims/is-core-module'
  oxc-parser: 'catalog:'
  shiki: 'catalog:'
  smartwrap: 'npm:@no-shims/smartwrap'
  vite: 'catalog:'

defines:
  - &babel ^7.28.0
  - &nolebase ^2.18.1
  - &shiki ^3.8.1
  - &unocss ^66.3.3
  - &vitest ^3.2.4
  - &vlt 3.0.4
  - &vue ^3.5.18
  - &rolldown ^1.0.0-beta.29
  - &oxc ^0.78.0

catalog:
  '@babel/parser': *babel
  '@babel/types': *babel

  '@vue/language-core': *vlt
  vue-tsc: *vlt

  '@vitest/coverage-v8': *vitest
  '@vitest/ui': *vitest
  vitest: *vitest

  '@unocss/eslint-plugin': *unocss
  '@unocss/nuxt': *unocss
  '@unocss/reset': *unocss
  unocss: *unocss

  '@vue/compiler-core': *vue
  '@vue/compiler-dom': *vue
  '@vue/compiler-sfc': *vue
  '@vue/shared': *vue
  vue: *vue

  '@shikijs/core': *shiki
  '@shikijs/transformers': *shiki
  '@shikijs/types': *shiki
  '@shikijs/vitepress-twoslash': *shiki
  shiki: *shiki

  '@nolebase/vitepress-plugin-enhanced-mark': *nolebase
  '@nolebase/vitepress-plugin-enhanced-readabilities': *nolebase
  '@nolebase/vitepress-plugin-git-changelog': *nolebase
  '@nolebase/vitepress-plugin-highlight-targeted-heading': *nolebase

  '@astrojs/vue': ^5.1.0
  '@iconify-json/logos': ^1.2.5
  '@iconify-json/ri': ^1.2.5
  '@nuxt/devtools': ^2.6.2
  '@nuxt/kit': ^4.0.2
  '@nuxt/schema': ^4.0.2
  '@rolldown/pluginutils': *rolldown
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rspack/core': ^1.4.10
  '@stylexjs/stylex': ^0.14.3
  '@sxzz/eslint-config': ^7.1.1
  '@sxzz/prettier-config': ^2.2.3
  '@sxzz/test-utils': ^0.5.7
  '@types/node': ^24.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vueuse/core': ^13.6.0
  ast-kit: ^2.1.1
  ast-walker-scope: ^0.8.1
  astro: ^5.12.5
  bumpp: ^10.2.1
  change-case: ^5.4.4
  cspell: ^9.2.0
  esbuild: ^0.25.8
  eslint: ^9.32.0
  expect-type: ^1.2.2
  fast-glob: ^3.3.3
  get-port: ^7.1.0
  jiti: ^2.5.1
  local-pkg: ^1.1.1
  magic-string: ^0.30.17
  magic-string-ast: ^1.0.0
  monoman: ^0.7.1
  muggle-string: ^0.4.1
  neverthrow: ^8.2.0
  nuxt: ^4.0.2
  oxc-parser: *oxc
  oxc-resolver: ^11.6.0
  oxc-transform: *oxc
  pkg-types: ^2.2.0
  prettier: ^3.6.2
  publint: ^0.3.12
  quansync: ^0.2.10
  quasar: ^2.18.2
  radix-vue: ^1.9.17
  rimraf: ^6.0.1
  rolldown: *rolldown
  rollup: ^4.46.1
  rollup-plugin-dts: ^6.2.1
  sirv: ^3.0.1
  taze: ^19.1.0
  ts-macro: ^0.3.1
  tsdown: ^0.13.0
  tsx: ^4.20.3
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unconfig: ^7.3.2
  unplugin: ^2.3.5
  unplugin-combine: ^2.0.0
  unplugin-macros: ^0.17.1
  unplugin-oxc: ^0.4.8
  unplugin-quansync: ^0.4.3
  unplugin-raw: ^0.5.0
  unplugin-unused: ^0.5.1
  unplugin-utils: ^0.2.4
  unplugin-vue: ^7.0.0
  vite: ^7.0.6
  vite-hyper-config: ^0.7.0
  vite-plugin-inspect: ^11.3.2
  vite-plugin-stylex: ^0.13.0
  vite-plugin-vue-devtools: ^8.0.0
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.6.1
  vitepress-plugin-llms: ^1.7.2
  webpack: ^5.101.0

peerDependencyRules:
  ignoreMissing:
    - search-insights
