packages:
  - packages/*
  - playground/*
  - docs

overrides:
  '@netlify/functions': '-'
  '@rolldown/pluginutils': 'catalog:'
  '@shikijs/core': 'catalog:'
  '@shikijs/transformers': 'catalog:'
  '@shikijs/types': 'catalog:'
  '@vitejs/plugin-vue': 'catalog:'
  '@vitejs/plugin-vue-jsx': 'catalog:'
  '@vue/language-core': 'catalog:'
  is-core-module: npm:@no-shims/is-core-module
  oxc-parser: 'catalog:'
  shiki: 'catalog:'
  smartwrap: npm:@no-shims/smartwrap
  vite: 'catalog:'
  oxc-minify: 'catalog:'
  oxc-transform: 'catalog:'
  unplugin-vue-router>@vue-macros/common: latest

defines:
  - &babel ^7.28.2
  - &nolebase ^2.18.2
  - &shiki ^3.12.0
  - &unocss ^66.4.2
  - &vitest ^3.2.4
  - &vlt 3.0.6
  - &vue ^3.5.20
  - &rolldown ^1.0.0-beta.34
  - &oxc ^0.85.0
  - &nuxt ^4.0.3

catalog:
  '@babel/parser': *babel
  '@babel/types': *babel

  '@vue/language-core': *vlt
  vue-tsc: *vlt

  '@vitest/coverage-v8': *vitest
  '@vitest/ui': *vitest
  vitest: *vitest

  '@unocss/eslint-plugin': *unocss
  '@unocss/nuxt': *unocss
  '@unocss/reset': *unocss
  unocss: *unocss

  '@vue/compiler-core': *vue
  '@vue/compiler-dom': *vue
  '@vue/compiler-sfc': *vue
  '@vue/shared': *vue
  vue: *vue

  '@shikijs/core': *shiki
  '@shikijs/transformers': *shiki
  '@shikijs/types': *shiki
  '@shikijs/vitepress-twoslash': *shiki
  shiki: *shiki

  '@nolebase/vitepress-plugin-enhanced-mark': *nolebase
  '@nolebase/vitepress-plugin-enhanced-readabilities': *nolebase
  '@nolebase/vitepress-plugin-git-changelog': *nolebase
  '@nolebase/vitepress-plugin-highlight-targeted-heading': *nolebase

  oxc-minify: *oxc
  oxc-parser: *oxc
  oxc-resolver: ^11.7.1
  oxc-transform: *oxc

  '@astrojs/vue': ^5.1.0
  '@iconify-json/logos': ^1.2.9
  '@iconify-json/ri': ^1.2.5
  '@nuxt/devtools': ^2.6.3
  '@nuxt/kit': *nuxt
  '@nuxt/schema': *nuxt
  '@rolldown/pluginutils': *rolldown
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rspack/core': ^1.5.1
  '@stylexjs/stylex': ^0.15.3
  '@sxzz/eslint-config': ^7.1.4
  '@sxzz/prettier-config': ^2.2.4
  '@sxzz/test-utils': ^0.5.10
  '@types/node': ^24.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vueuse/core': ^13.8.0
  ast-kit: ^2.1.2
  ast-walker-scope: ^0.8.2
  astro: ^5.13.5
  bumpp: ^10.2.3
  change-case: ^5.4.4
  cspell: ^9.2.0
  esbuild: ^0.25.9
  eslint: ^9.34.0
  expect-type: ^1.2.2
  fast-glob: ^3.3.3
  get-port: ^7.1.0
  jiti: ^2.5.1
  local-pkg: ^1.1.2
  magic-string: ^0.30.18
  magic-string-ast: ^1.0.2
  monoman: ^0.7.2
  muggle-string: ^0.4.1
  neverthrow: ^8.2.0
  nuxt: *nuxt
  pkg-types: ^2.3.0
  prettier: ^3.6.2
  publint: ^0.3.12
  quansync: ^0.2.11
  quasar: ^2.18.2
  radix-vue: ^1.9.17
  rimraf: ^6.0.1
  rolldown: *rolldown
  rollup: ^4.49.0
  rollup-plugin-dts: ^6.2.3
  sirv: ^3.0.1
  taze: ^19.3.0
  ts-macro: ^0.3.4
  tsdown: ^0.14.2
  tsx: ^4.20.5
  type-fest: ^5.0.0
  typescript: ^5.9.2
  unconfig: ^7.3.3
  unplugin: ^2.3.9
  unplugin-combine: ^2.1.2
  unplugin-macros: ^0.18.0
  unplugin-oxc: ^0.5.1
  unplugin-quansync: ^0.4.4
  unplugin-raw: ^0.6.1
  unplugin-unused: ^0.5.2
  unplugin-utils: ^0.3.0
  unplugin-vue: ^7.0.1
  vite: ^7.1.3
  vite-hyper-config: ^0.7.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-stylex: ^0.13.0
  vite-plugin-vue-devtools: ^8.0.1
  vitepress: ^2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.3
  vitepress-plugin-llms: ^1.7.3
  webpack: ^5.101.3

peerDependencyRules:
  ignoreMissing:
    - search-insights
