# eslint yml/sort-keys: ['error', { pathPattern: "^catalog$", order: { type: asc }, allowLineSeparatedGroups: true }]

defines:
  - &babel ^7.26.9
  - &nolebase ^2.15.0
  - &shiki ^3.1.0
  - &unocss ^66.1.0-beta.3
  - &vitest ^3.0.7
  - &volar 2.2.4
  - &vue ^3.5.13

catalog:
  '@babel/parser': *babel
  '@babel/types': *babel

  '@vue/language-core': *volar
  vue-tsc: *volar

  '@vitest/coverage-v8': *vitest
  '@vitest/ui': *vitest
  vitest: *vitest

  '@unocss/eslint-plugin': *unocss
  '@unocss/nuxt': *unocss
  '@unocss/reset': *unocss
  unocss: *unocss

  '@vue/compiler-core': *vue
  '@vue/compiler-dom': *vue
  '@vue/compiler-sfc': *vue
  '@vue/reactivity': *vue
  '@vue/runtime-core': *vue
  '@vue/runtime-dom': *vue
  '@vue/shared': *vue
  vue: *vue

  '@shikijs/core': *shiki
  '@shikijs/transformers': *shiki
  '@shikijs/types': *shiki
  '@shikijs/vitepress-twoslash': *shiki
  shiki: *shiki

  '@nolebase/vitepress-plugin-enhanced-mark': *nolebase
  '@nolebase/vitepress-plugin-enhanced-readabilities': *nolebase
  '@nolebase/vitepress-plugin-git-changelog': *nolebase
  '@nolebase/vitepress-plugin-highlight-targeted-heading': *nolebase

  '@stylexjs/stylex': ^0.11.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vueuse/core': ^12.7.0
  ast-walker-scope: ^0.7.0
  esbuild: ^0.25.0
  eslint: ^9.21.0
  magic-string: ^0.30.17
  prettier: ^3.5.2
  rollup: ^4.34.9
  typescript: ^5.8.2
  unplugin: ^2.2.0
  unplugin-oxc: ^0.2.5
  unplugin-vue: ^6.0.0
  vite: ^6.2.0
  vite-plugin-stylex: ^0.13.0
  vitepress: ^2.0.0-alpha.2

packages:
  - packages/*
  - playground/*
  - docs
