# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.5.0
  '@vue/compiler-dom': ^3.5.0
  '@vue/compiler-sfc': ^3.5.0
  '@vue/language-core': 2.0.29
  '@vue/reactivity': ^3.5.0
  '@vue/runtime-core': ^3.5.0
  '@vue/runtime-dom': ^3.5.0
  '@vue/shared': ^3.5.0
  typescript: 5.6.1-rc
  unplugin: ^1.12.3
  vite: ^5.4.3
  vue: ^3.5.0
  vue-tsc: 2.0.29
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
