# eslint yml/sort-keys: 'error'

catalog:
  '@stylexjs/stylex': ^0.10.0
  '@vue/compiler-core': ^3.5.13
  '@vue/compiler-dom': ^3.5.13
  '@vue/compiler-sfc': ^3.5.13
  '@vue/language-core': 2.1.10
  '@vue/reactivity': ^3.5.13
  '@vue/runtime-core': ^3.5.13
  '@vue/runtime-dom': ^3.5.13
  '@vue/shared': ^3.5.13
  esbuild: ^0.24.2
  rollup: ^4.30.1
  typescript: ^5.7.2
  unplugin: ^1.16.1
  vite: ^6.0.7
  vite-plugin-stylex: ^0.13.0
  vue: ^3.5.13
  vue-tsc: 2.2.0
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
